resources:
- repo: self

variables:
  RootLocalPath: 'C:\drop'
  TestsPathName: 'unit-tests'

jobs:
- job: RunTests
  strategy:
    maxParallel: 4
    matrix:
      OnSharePoint2013:
        deployThisSharePointVersion: variables['Deployment.ProvisionSharePoint2013']
        sharePointVersion: 2013
      OnSharePoint2016:
        deployThisSharePointVersion: variables['Deployment.ProvisionSharePoint2016']
        sharePointVersion: 2016
      OnSharePoint2019:
        deployThisSharePointVersion: variables['Deployment.ProvisionSharePoint2019']
        sharePointVersion: 2019
      OnSharePointSubscription:
        deployThisSharePointVersion: variables['Deployment.ProvisionSharePointSubscription']
        sharePointVersion: SE
  displayName: Run integration tests
  #condition: eq(variables['deployThisSharePointVersion'], 'yes') # Not working: variables['deployThisSharePointVersion'] is evaluated to Null
  timeoutInMinutes: 30
  pool:
    name: $(System.TeamProject)-Tests-$(sharePointVersion)
  steps:
  - checkout: none #skip checking out the default repository resource
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'

  - task: VSTest@3
    displayName: 'Run Visual Studio tests'
    inputs:
      searchFolder: '$(RootLocalPath)/$(TestsPathName)/$(System.TeamProject)-unit-tests/release'
      vsTestVersion: toolsInstaller
      runSettingsFile: '$(RootLocalPath)/$(TestsPathName)/DTLServer.runsettings'
      overrideTestrunParameters: '$(Tests.OverrideTestrunParameters)'
      codeCoverageEnabled: $(Tests.CodeCoverageEnabled)
      otherConsoleOptions: '/Platform:x64'
      testRunTitle: '$(System.TeamProject)-Tests-SP$(sharePointVersion)'
      platform: '$(BuildPlatform)'
      configuration: $(Tests.BuildConfiguration)
      testAssemblyVer2: |
        **\$(System.TeamProject)*test*.dll
